on:
  push:
    branches:
      -master
      
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      -uses: actions/checkout@v3  
      
      run: docker login --username mohmedsabry --password dckr_pat_CrI4a0RzYdpEtSaXBwU3onMO5Gg
      run: docker build -t mohmedsabry/img .
      
      run: docker push mohmedsabry/img
