on:
  push: 
    branches:
      - master



jobs:
  build:
    runs-on: windows-latest 


    steps:
      - uses: actions/checkout@v3  

      - name: "Login to Docker hub"
        run: docker login --username mohmedsabry --password Mohmed@195

      - name: "Building Docker Image"
        run: docker build -t mohmedsabry/image .
      
      - name: "Pushing to Docker hub"
        run: docker push mohmedsabry/image

